name: Syntax

on:
  push:
    branches:
      - 'SM-*'

jobs:
  find_merge_conflicts:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      # Checkout the source code so there are some files to look at.
      - uses: actions/checkout@v4
      # Run the actual merge conflict finder
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0
  php_syntax_check:
    runs-on: ubuntu-latest
    name: PHP Syntax
    needs: [find_merge_conflicts]
    steps:
      # Checkout the source code so there are some files to look at.
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check magic numbers
        run: composer phpmnd

      - name: Check PHP Stan
        run: composer phpstan

      - name: Check PHP Code Sniffer
        run: composer phpcs

  javascript_syntax_check:
    runs-on: ubuntu-latest
    name: JavaScript Syntax Check
    needs: [find_merge_conflicts]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm  # Ruta donde npm guarda la caché
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install Node.js dependencies
        run: npm install

      - name: Run ESLint
        run: npm run linter