name: Unit Tests

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  find_merge_conflicts:
    runs-on: ubuntu-latest
    name: Find merge conflicts
    steps:
      # Checkout the source code so there are some files to look at.
      - uses: actions/checkout@v4
      # Run the actual merge conflict finder
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0
  react_test:
    runs-on: ubuntu-latest
    name: Run React Tests
    needs: [find_merge_conflicts]
    steps:
      # Checkout del código fuente
      - uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Cambia esto a la versión que necesites

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm  # Ruta donde npm guarda la caché
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      # Instalar dependencias
      - name: Install Dependencies
        run: npm install

      # Ejecutar los tests de React
      - name: Run React Tests
        run: LARAVEL_BYPASS_ENV_CHECK=1 npm run test

  laravel_test:
    runs-on: ubuntu-latest
    name: Run Laravel Tests
    needs: [find_merge_conflicts]
    steps:
      # Checkout del código fuente
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ./vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            composer-${{ runner.os }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      # Ejecutar los tests de Laravel
      - name: Run Laravel Tests
        run: composer test  # Ajusta este comando según tu configuración
